### ISSUE TITLE
Symbole Acteur

### ISSUE THREAD

**Issue by jean-felix** [Seikomi/Vitameal#4]
Avec Papyrus, dans le cas d'utilisation de la génération automatique des menus, le symbole de l'acteur n'est pas le symbole standard (voir image .png) et je ne sais pas pourquoi (je ne suis pas arrivé à le configurer dans Eclipse).
Nicolas, tu as une idée ?

**Comment by Seikomi** [comment]
Je ne sais pas vraiment, tu peux éditer le svg (avec inkscape) remplacer l'image de l'acteur
