### ISSUE TITLE
Fichier pas à sa place

### ISSUE THREAD

**Issue by jean-felix** [Seikomi/Vitameal#5]
Le fichier suivant ne fait pas partie de la génération des menus; merci de le déplacer dans le bon dossier:
https://github.com/Seikomi/Vitameal/blob/master/Documentation/CasDUtilisations/MenuGen/usecase1.jpg

**Comment by othmanisonia** [comment]
Je m'en occupe ce soir, en attendant je vous envoie le compte rendu par mail.
