### ISSUE TITLE
A propos du .gitignore

### ISSUE THREAD

**Issue by Seikomi** [Seikomi/Vitameal#6]
Après discutions avec mes collèges autour de la gestion du .gitignore et des recherches personnelles, voici se que j'ai trouvé (issus de stackoverflow) : 

*Début du message*

First of all, as many others already said, your `.gitignore` **should be tracked by Git** (and should therefore not be ignored). Let me explain why.

(commit the `.gitignore` file, and use a global `.gitignore` to ignore files that are created by your IDE or operating system)

Git is, as you probably already know, a distributed version control system. This means that it allows you to switch back and forth between different versions (even if development has diverged into different branches) and it also allows multiple developers to work on the same project.

Although tracking your .gitignore also has benefits when you switch between snapshots, the most important reason for committing it is that you'll want to share the file with other developers who are working on the same project. By committing the file into Git, other contributers will automatically get the .gitignore file when they clone the repository, so they won't have to worry about accidentally committing a file that shouldn't be committed (such as log files, cache directories, database credentials, etc.). And if at some point the project's .gitignore is updated, they can simply pull in those changes instead of having to edit the file manually.

Of course, there will be some files and folders that you'll want to ignore, but that are specific for you, and don't apply to other developers. However, those should not be in the project's `.gitignore`. There are two other places where you can ignore files and folders

Files and folders that are created by your operating system or IDE should be placed in a global `.gitignore`. The benefit is that this .gitignore is applied to all repositories on your computer, so you don't have to repeat this for every repository. And it's not shared with other developers, since they might be using a different operating system and/or IDE.

Files that don't belong in the project's `.gitignore`, nor in the global `.gitignore`, can be ignored using explicit repository excludes in your_project_directory/.git/info/exclude. This file will not be shared with other developers, and is specific for that single repository.

*Fin du message*

Du coup, il fraudai définir un `.gitignore` commun au projet. Et suivre les recommandations du monsieur en cas de fichiers spécifiques de nos poste de dev.

**Comment by jean-felix** [comment]
Voici le contenu de mon `.gitignore`:

>*.[oa]
>*~
>*.synctex.gz
>Thumbs.db
>.gitignore*
>.DS_Store
>.#*
>.project
>.settings
>*.md.html

vois-tu des choses à ajouter, à enlever ?

**Comment by Seikomi** [comment]
le mien ressemble à ça :
```
.gitignore

.settings
*.yml
/target/
.classpath
.project
/bin/
*.md.html
*.dia~


*.nav
*.snm
*.aux
*.glo
*.ist
*.lof
*.log
*.lot
*.out
*.synctex.gz
*.toc
```

**Comment by jean-felix** [comment]
le tiens est plus complet, je te propose de l'adopter avec cela en plus:

*.[oa]  
*~  
.#*

**Comment by Seikomi** [comment]
pourquoi ~ et .# ?

**Comment by jean-felix** [comment]
ce sont des extensions utilisées par emacs, pour noter des fichiers temporaires ou des versions précédentes.
C'est "point~", mais le point n'apparait pas ...
J'ai aussi noté ".#étoile", mais l'étoile n'appartait pas ...

**Comment by Seikomi** [comment]
ok je créer un .gitignore commun que l'on enrichira au fur et à mesure

**Comment by Seikomi** [comment]
C'est fait
