### ISSUE TITLE
Latex: Erreur de compilation du rapport

### ISSUE THREAD

**Issue by jean-felix** [Seikomi/Vitameal#7]
Il y a une erreur lors de la compilation Latex du rapport. C'est le fichier "uc_renseigner_profil_patient.tex" qui est en cause. Merci de le corriger et de vérifier qu'il n'y a pas d'erreur de compilation avant de remonter un fichier.

**Comment by othmanisonia** [comment]
Fichier modifié et compilé, a priori tout va bien!
